# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yJ5MuvhRL9Rk0IsU7ZUYj0fSy4ipuGib
"""

import os

# 1. CLEANUP & AUTH (Deletes old data to prevent "replace?" prompts)
!rm -rf urban_data urban-sound-8k.zip
os.environ['KAGGLE_USERNAME'] = "vivekkumarsharma"
os.environ['KAGGLE_KEY'] = "40a4c0cc2ab30d22636e082a9243e6e2"

print("Installing required libraries...")
!pip install librosa tqdm tensorflow scikit-learn -q

import librosa
import numpy as np
import pandas as pd
from tqdm import tqdm
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Activation

# 2. DATASET DOWNLOAD & UNZIP (Forced overwrite with -o)
print("Downloading UrbanSound8K...")
!kaggle datasets download -d rupakroy/urban-sound-8k
!unzip -qo urban-sound-8k.zip -d urban_data
print("Unzip complete.")

# 3. PATH VERIFICATION & FEATURE EXTRACTION
base_path = '/content/urban_data/UrbanSound8K/UrbanSound8K/audio/'
metadata = pd.read_csv('/content/urban_data/UrbanSound8K.csv')
relevant_metadata = metadata[metadata['classID'].isin([1, 8])]

features = []
print(f"Extracting features for {len(relevant_metadata)} samples...")

for index, row in tqdm(relevant_metadata.iterrows(), total=relevant_metadata.shape[0]):
    file_path = os.path.join(base_path, f'fold{row["fold"]}', str(row["slice_file_name"]))

    if os.path.exists(file_path):
        try:
            # sr=None is crucial to bypass resampy issues
            audio, sample_rate = librosa.load(file_path, sr=None)
            mfccs = librosa.feature.mfcc(y=audio, sr=sample_rate, n_mfcc=40)
            features.append([np.mean(mfccs.T, axis=0), row['classID']])
        except Exception:
            continue

# 4. ARRAY CONVERSION & MODEL TRAINING
if len(features) > 0:
    features_df = pd.DataFrame(features, columns=['feature', 'class_id'])
    X = np.array(features_df.feature.tolist())
    y = np.array(features_df.class_id.tolist())

    le = LabelEncoder()
    y_encoded = to_categorical(le.fit_transform(y))
    X_train, X_test, y_train, y_test = train_test_split(X, y_encoded, test_size=0.2, random_state=42)

    print("\n--- Starting ANN Training ---")
    model = Sequential([
        Dense(256, input_shape=(40,), activation='relu'),
        Dropout(0.3),
        Dense(128, activation='relu'),
        Dropout(0.3),
        Dense(2, activation='softmax')
    ])

    model.compile(loss='categorical_crossentropy', metrics=['accuracy'], optimizer='adam')
    model.fit(X_train, y_train, batch_size=32, epochs=50, validation_data=(X_test, y_test))

    model.save("siren_horn_detector.h5")
    print("\nSUCCESS: Model saved as siren_horn_detector.h5")
else:
    print("\nERROR: No features extracted. The base_path is likely still wrong.")

from google.colab import files
files.download('siren_horn_detector.h5')

!pip install ultralytics moviepy==1.0.3 librosa -q

# 1. INSTALL DEPENDENCIES (Run this once)
!pip install ultralytics moviepy==1.0.3 librosa -q

import cv2
import librosa
import numpy as np
import tensorflow as tf
import os
from ultralytics import YOLO
from moviepy.editor import VideoFileClip
from google.colab.patches import cv2_imshow

# 2. LOAD THE MODELS
# Using your specific filename '2ndtimebest.pt'
vision_path = '2ndtimebest.pt'
audio_path = 'siren_horn_detector.h5'

print("--- Initializing Emergency System ---")
if os.path.exists(vision_path) and os.path.exists(audio_path):
    vision_model = YOLO(vision_path)
    audio_model = tf.keras.models.load_model(audio_path)
    print("✅ All systems online.")
else:
    print("❌ Error: Ensure '2ndtimebest.pt' and 'siren_horn_detector.h5' are in the sidebar.")

# 3. THE FUSION ENGINE
def run_magic(video_input):
    if not os.path.exists(video_input):
        print(f"❌ Video {video_input} not found!")
        return

    cap = cv2.VideoCapture(video_input)
    fps = cap.get(cv2.CAP_PROP_FPS)

    # Extract audio track once for efficiency
    print("🔊 Extracting audio for frequency analysis...")
    video_clip = VideoFileClip(video_input)
    audio_data = video_clip.audio.to_soundarray(fps=22050)
    audio_mono = np.mean(audio_data, axis=1) # Convert to mono

    frame_count = 0
    print("🚀 Processing Video...")

    while cap.isOpened():
        ret, frame = cap.read()
        if not ret: break

        # A. Vision Logic (YOLOv8)
        results = vision_model(frame, conf=0.5, verbose=False)
        v_detected = len(results[0].boxes) > 0

        # B. Audio Logic (ANN) - Process 1 sec of audio every second
        current_sec = int(frame_count / fps)
        a_detected = False
        try:
            start_idx = int(current_sec * 22050)
            end_idx = int((current_sec + 1) * 22050)
            chunk = audio_mono[start_idx:end_idx]

            if len(chunk) > 0:
                mfccs = librosa.feature.mfcc(y=chunk, sr=22050, n_mfcc=40)
                mfccs_scaled = np.mean(mfccs.T, axis=0).reshape(1, 40)
                # Prediction: 1 is Siren (class 8), 0 is Horn (class 1)
                pred = audio_model.predict(mfccs_scaled, verbose=0)
                a_detected = np.argmax(pred) == 1
        except:
            pass

        # C. Sensor Fusion Decision
        if v_detected and a_detected:
            status, color = "!! EMERGENCY !!", (0, 0, 255) # Red
        elif v_detected:
            status, color = "WARNING: VISUAL ONLY", (0, 165, 255) # Orange
        elif a_detected:
            status, color = "WARNING: SIREN ONLY", (0, 255, 255) # Yellow
        else:
            status, color = "SYSTEM: CLEAR", (0, 255, 0) # Green

        # D. Visualization
        if v_detected:
            frame = results[0].plot() # Draw YOLO bounding boxes

        cv2.rectangle(frame, (0, 0), (650, 70), (0,0,0), -1) # Status box
        cv2.putText(frame, status, (20, 50), cv2.FONT_HERSHEY_SIMPLEX, 1.2, color, 3)

        # Show every 15th frame (to prevent Colab from freezing)
        if frame_count % 15 == 0:
            cv2_imshow(frame)

        frame_count += 1

    cap.release()
    print("✅ Finished processing.")

# 4. EXECUTION
# Change 'ambulance_test.mp4' to your actual uploaded video filename
# run_magic('ambulance_test.mp4')

# Install the downloader
!pip install yt-dlp -q

# This command downloads a high-quality MP4 and names it 'test_ambulance.mp4'
!yt-dlp -f "bestvideo[ext=mp4]+bestaudio[ext=m4a]/mp4" --output "test_ambulance.mp4" "https://www.youtube.com/watch?v=G0faYBLfCyU"

print("✅ Download finished! You now have 'test_ambulance.mp4' in your folder.")

def run_magic(video_input):
    if not os.path.exists(video_input):
        print(f"❌ Video {video_input} not found!")
        return

    # 1. Setup Video
    cap = cv2.VideoCapture(video_input)
    fps = cap.get(cv2.CAP_PROP_FPS)
    total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))

    # 2. FIXED AUDIO EXTRACTION (Using Librosa instead of MoviePy)
    print("🔊 Extracting audio via Librosa...")
    try:
        # Librosa can read audio directly from MP4 files
        audio_mono, sr = librosa.load(video_input, sr=22050)
    except Exception as e:
        print(f"⚠️ Audio extraction failed: {e}. System will run Vision-only.")
        audio_mono = np.zeros(int(total_frames/fps * 22050)) # Fallback to silence

    frame_count = 0
    print("🚀 Processing Video...")

    while cap.isOpened():
        ret, frame = cap.read()
        if not ret: break

        # A. Vision Logic (YOLOv8)
        results = vision_model(frame, conf=0.5, verbose=False)
        v_detected = len(results[0].boxes) > 0

        # B. Audio Logic (ANN) - Process 1 sec of audio
        current_sec = int(frame_count / fps)
        a_detected = False
        try:
            start_idx = int(current_sec * 22050)
            end_idx = int((current_sec + 1) * 22050)
            chunk = audio_mono[start_idx:end_idx]

            if len(chunk) > 2000: # Ensure we have enough data
                mfccs = librosa.feature.mfcc(y=chunk, sr=22050, n_mfcc=40)
                mfccs_scaled = np.mean(mfccs.T, axis=0).reshape(1, 40)
                pred = audio_model.predict(mfccs_scaled, verbose=0)
                a_detected = np.argmax(pred) == 1
        except:
            pass

        # C. Sensor Fusion Decision
        if v_detected and a_detected:
            status, color = "!! EMERGENCY !!", (0, 0, 255) # Red
        elif v_detected:
            status, color = "WARNING: VISUAL ONLY", (0, 165, 255) # Orange
        elif a_detected:
            status, color = "WARNING: SIREN ONLY", (0, 255, 255) # Yellow
        else:
            status, color = "SYSTEM: CLEAR", (0, 255, 0) # Green

        # D. Visualization
        if v_detected:
            frame = results[0].plot()

        cv2.rectangle(frame, (0, 0), (650, 70), (0,0,0), -1)
        cv2.putText(frame, status, (20, 50), cv2.FONT_HERSHEY_SIMPLEX, 1.2, color, 3)

        # Show every 15th frame
        if frame_count % 15 == 0:
            cv2_imshow(frame)

        frame_count += 1

    cap.release()
    print("✅ Finished processing.")

run_magic('test_ambulance.mp4')

def save_fusion_video(video_input, output_name='Output_Demo.mp4'):
    cap = cv2.VideoCapture(video_input)
    fps = cap.get(cv2.CAP_PROP_FPS)
    w = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    h = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))

    # Define the codec and create VideoWriter object
    fourcc = cv2.VideoWriter_fourcc(*'MP4V')
    out = cv2.VideoWriter(output_name, fourcc, fps, (w, h))

    # Re-using your logic to process every frame for the final video
    audio_mono, sr = librosa.load(video_input, sr=22050)
    frame_count = 0

    print("🎬 Generating final demonstration video...")
    while cap.isOpened():
        ret, frame = cap.read()
        if not ret: break

        results = vision_model(frame, conf=0.5, verbose=False)
        v_detected = len(results[0].boxes) > 0

        current_sec = int(frame_count / fps)
        a_detected = False
        try:
            chunk = audio_mono[int(current_sec*22050):int((current_sec+1)*22050)]
            if len(chunk) > 2000:
                mfccs = librosa.feature.mfcc(y=chunk, sr=22050, n_mfcc=40)
                mfccs_scaled = np.mean(mfccs.T, axis=0).reshape(1, 40)
                a_detected = np.argmax(audio_model.predict(mfccs_scaled, verbose=0)) == 1
        except: pass

        # Draw the same UI
        if v_detected: frame = results[0].plot()
        status = "!! EMERGENCY !!" if (v_detected and a_detected) else "SYSTEM: CLEAR"
        color = (0, 0, 255) if (v_detected and a_detected) else (0, 255, 0)

        cv2.rectangle(frame, (0, 0), (650, 70), (0,0,0), -1)
        cv2.putText(frame, status, (20, 50), cv2.FONT_HERSHEY_SIMPLEX, 1.2, color, 3)

        out.write(frame)
        frame_count += 1

    cap.release()
    out.release()
    print(f"✅ {output_name} created. Downloading now...")
    files.download(output_name)

# Run this to get your demo file
save_fusion_video('test_ambulance.mp4')

