# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UfkDtb2l1i3Dp4YRB7_AqpsDSx9YyLnd
"""

!pip install ultralytics roboflow librosa tensorflow kaggle

# 1. Download Dataset from Roboflow
from roboflow import Roboflow
rf = Roboflow(api_key="JLergG61YRw0kubzzIlQ")
project = rf.workspace("project-1-ryhzx").project("emergency-vehicle-9m8pi")
version = project.version(1)
dataset = version.download("yolov8")

# 2. Setup YOLOv8 and Begin Training
from ultralytics import YOLO

# Load the Nano model as requested
model = YOLO('yolov8n.pt')

# Train the model using your project's specific requirements
# We use 50 epochs as per your report's stable training guidelines
results = model.train(
    data=f"{dataset.location}/data.yaml",
    epochs=50,      # Aligned with your report's methodology
    imgsz=640,     # Standard resolution for robust detection [cite: 556]
    plots=True,     # Generates the Precision-Recall & Confusion Matrix plots [cite: 171]
    device=0       # Explicitly tells Colab to use the T4 GPU
)

from google.colab import drive
drive.mount('/content/drive')

import os
import shutil
from google.colab import files

# 1. Define paths
source_path = '/content/runs/detect/train/weights/best.pt'
drive_path = '/content/drive/MyDrive/emergency_vision_v8.pt'
local_name = 'emergency_vision_v8.pt'

# 2. Copy to Google Drive (Permanent backup)
try:
    shutil.copy(source_path, drive_path)
    print(f"✅ Model backed up to Google Drive at: {drive_path}")
except:
    print("Drive not mounted? Skipping Drive backup.")

# 3. Download to your Computer
if os.path.exists(source_path):
    print(f"🚀 Starting download to your computer...")
    files.download(source_path)
else:
    print("❌ Error: 'best.pt' not found in the expected directory.")

