# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yJ5MuvhRL9Rk0IsU7ZUYj0fSy4ipuGib
"""

import os

# 1. CLEANUP & AUTH (Deletes old data to prevent "replace?" prompts)
!rm -rf urban_data urban-sound-8k.zip
os.environ['KAGGLE_USERNAME'] = "vivekkumarsharma"
os.environ['KAGGLE_KEY'] = "40a4c0cc2ab30d22636e082a9243e6e2"

print("Installing required libraries...")
!pip install librosa tqdm tensorflow scikit-learn -q

import librosa
import numpy as np
import pandas as pd
from tqdm import tqdm
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Activation

# 2. DATASET DOWNLOAD & UNZIP (Forced overwrite with -o)
print("Downloading UrbanSound8K...")
!kaggle datasets download -d rupakroy/urban-sound-8k
!unzip -qo urban-sound-8k.zip -d urban_data
print("Unzip complete.")

# 3. PATH VERIFICATION & FEATURE EXTRACTION
base_path = '/content/urban_data/UrbanSound8K/UrbanSound8K/audio/'
metadata = pd.read_csv('/content/urban_data/UrbanSound8K.csv')
relevant_metadata = metadata[metadata['classID'].isin([1, 8])]

features = []
print(f"Extracting features for {len(relevant_metadata)} samples...")

for index, row in tqdm(relevant_metadata.iterrows(), total=relevant_metadata.shape[0]):
    file_path = os.path.join(base_path, f'fold{row["fold"]}', str(row["slice_file_name"]))

    if os.path.exists(file_path):
        try:
            # sr=None is crucial to bypass resampy issues
            audio, sample_rate = librosa.load(file_path, sr=None)
            mfccs = librosa.feature.mfcc(y=audio, sr=sample_rate, n_mfcc=40)
            features.append([np.mean(mfccs.T, axis=0), row['classID']])
        except Exception:
            continue

# 4. ARRAY CONVERSION & MODEL TRAINING
if len(features) > 0:
    features_df = pd.DataFrame(features, columns=['feature', 'class_id'])
    X = np.array(features_df.feature.tolist())
    y = np.array(features_df.class_id.tolist())

    le = LabelEncoder()
    y_encoded = to_categorical(le.fit_transform(y))
    X_train, X_test, y_train, y_test = train_test_split(X, y_encoded, test_size=0.2, random_state=42)

    print("\n--- Starting ANN Training ---")
    model = Sequential([
        Dense(256, input_shape=(40,), activation='relu'),
        Dropout(0.3),
        Dense(128, activation='relu'),
        Dropout(0.3),
        Dense(2, activation='softmax')
    ])

    model.compile(loss='categorical_crossentropy', metrics=['accuracy'], optimizer='adam')
    model.fit(X_train, y_train, batch_size=32, epochs=50, validation_data=(X_test, y_test))

    model.save("siren_horn_detector.h5")
    print("\nSUCCESS: Model saved as siren_horn_detector.h5")
else:
    print("\nERROR: No features extracted. The base_path is likely still wrong.")

from google.colab import files
files.download('siren_horn_detector.h5')

